[project]
name = "matthazley-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.5",
    "markdown>=3.7",
    "weasyprint>=64.0",
]
